# Generated by Django 4.2.5 on 2023-09-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='headertitle',
            name='body',
            field=models.TextField(default='front-end,back-end'),
        ),
    ]
